### ISSUE TITLE
Create Istio.rules in a proper namespace

### ISSUE THREAD

**Issue by songbinliu** [songbinliu/appMetric#3]
**Problem**
We have defined [metrics, prometheus handler, and rule](https://github.com/songbinliu/appMetric/blob/master/scripts/istio/ip.turbo.metric.yaml)  to tell Istio to export Pods/Services metrics to Prometheus.

However, if the `rule` is defined in `default` namespace, then in default settings of  [Istio 0.7.1](https://github.com/istio/istio/tree/release-0.7), we can only get the metrics for Pods/Services  in the `default` namespace.

```yaml
# Rule to send metric instances to a Prometheus handler
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: turbo
  namespace: default
spec:
  match: context.protocol == "http"
  actions:
  - handler: turbohandler.prometheus.default
    instances:
    - turbosvclatency.metric.default
    - turbosvcrequestcount.metric.default
    - turbopodlatency.metric.default
    - turbopodrequestcount.metric.default
---
```

**Reason**
When to [report](https://github.com/istio/istio/blob/62110d4f0373a7613e57b8a4d559ded9cb6a1cc8/mixer/pkg/runtime2/dispatcher/dispatcher.go#L137) an `Attribute bag`, Istio will send it to a set of destination handlers.
Istio [finds the set of destination handlers by the namespace in the value of `destination.uid` in the `Attribute bag`](https://github.com/istio/istio/blob/62110d4f0373a7613e57b8a4d559ded9cb6a1cc8/mixer/pkg/runtime2/dispatcher/dispatcher.go#L199)(here is [detail](https://github.com/istio/istio/blob/62110d4f0373a7613e57b8a4d559ded9cb6a1cc8/mixer/pkg/runtime2/routing/table.go#L120)).

However, the handlers set is created according to the `namespace` of `rule` ([details](https://github.com/istio/istio/blob/62110d4f0373a7613e57b8a4d559ded9cb6a1cc8/mixer/pkg/runtime2/routing/builder.go#L144)). 

Thus, if the rule `turbo` is defined in  namespace `default`, then we can only monitor the metrics of Pods/Services in the namespace `default`. But our purpose is to monitor the Pods/Services in **all** the namespaces.

**Solution**
Istio provides a way to handle this:  **Define the `rules` in the `configDefaultNamespace` of  `mixers`.**

The default value of the `configDefaultNamespace` is `istio-system`. All the rules defined in that namespace will be used to generate a default set of handlers.

This default set of handlers will be:
1. Added to the other namespaces if these namespaces has any other handler([detail](https://github.com/istio/istio/blob/62110d4f0373a7613e57b8a4d559ded9cb6a1cc8/mixer/pkg/runtime2/routing/builder.go#L189)).
       **Or**
2. Used if that namespace does not have any other handler ([detail](https://github.com/istio/istio/blob/62110d4f0373a7613e57b8a4d559ded9cb6a1cc8/mixer/pkg/runtime2/routing/table.go#L131)).

**Comment by songbinliu** [comment]
So if we want to monitor the Pods/Services of all the namespaces, then define the rule like this:
```yaml
# Rule to send metric instances to a Prometheus handler
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: turbo
  namespace: istio-system
spec:
  match: context.protocol == "http"
  actions:
  - handler: turbohandler.prometheus.default
    instances:
    - turbosvclatency.metric.default
    - turbosvcrequestcount.metric.default
    - turbopodlatency.metric.default
    - turbopodrequestcount.metric.default
```
Note that: we only change the namespace from `default` to `istio-system`.  The namespaces of the `metrics` and `handler` can be any namespace.


And if we want to monitor the Pods/Services in a particular namespace, then define the `rule` in that particular namespace.
